apiVersion: 1

datasources:
  - name: Cursor PostgreSQL
    type: postgres
    uid: postgres-cursor
    access: proxy
    url: 172.16.57.201:5432
    user: postgres
    database: postgres
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: postgres
